CFLASGS=-Wall -q

clean:
	rm -f exam1
	rm -f exam2
	rm -f exam3
	rm -f exam4
	rm -f exam5
	rm -f exam6
	rm -f exam7
	rm -f exam8
	rm -f exam9
	rm -f exam10
	rm -f exam11
	rm -f exam12
	rm -f exam13
	rm -f exam14
	rm -f exam15
	rm -f exam16
	rm -f exam17
	rm -f exam18
	rm -f exam19
	rm -f exam20
